In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as st
import sklearn.model_selection as sk_model_sel
import sklearn.linear_model as lm
from sklearn.preprocessing import OneHotEncoder

## Задача 1

Вы работаете аналитиком в компании по продажи мороженного в парках. В компании участились случаи, когда на конец дня остаётся не распроданное мороженное, а в некоторые дни наоборот - не хватает мороженного для покупателей. Необходимо научиться предсказывать продажи завтрашнего дня. Для этого необходимо построить модель линейной регрессии продаж мороженного, исходя из факторов продаж [’температура’, ‘влажность’]

При построении модели учесть:

Использовать библиотеку sklearn
Для разбиения на выборки использовать функцию train_test_split и параметр random_state = 42. Размер тестовой выборки 15%
Вывести значения прогнозной модели для тестовой выборки, округлённых до целого.
Исходные данные

Данные находятся в файле data.csv.
Разделитель значений - точка с запятой. Разделителем дробных чисел применяется запятая. В таблице даны три столбца. Названия столбцов - показаны ниже.

Дана таблица с тремя столбцами:
- продажи - продажи мороженного в штуках
- температура - температура воздуха на улице в градусах Цельсия
- влажность - влажность воздуха в процентах

   температура  влажность  продажи
0           17         41       93
1           17         79       96
2           17         73       97
3           18         64      101
4           18         80      102
5           18         67      104
6           19         60      115
7           19         76      103
8           22         55      135
9           22         65      119

In [ ]:
df = pd.read_csv('7_1.csv',sep=';', encoding='cp1251', skipinitialspace=True, decimal=',')
df = df.dropna()
X = df[['температура', 'влажность']]
y = df['продажи']
X_train, X_test, y_train, y_test = sk_model_sel.train_test_split(X, y, random_state=42, test_size=0.15)
model = lm.LinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
y_pred_rounded = np.round(y_pred).astype(float)
print(y_pred_rounded)

In [ ]:
[167. 159. 153. 127. ....]

## Задача 2

Вы всё также работаете аналитиком в компании по продажи мороженного в парках. И проблема всё таже - в компании участились случаи, когда на конец дня остаётся не распроданное мороженное, а в некоторые дни наоборот - не хватает мороженного для покупателей. Необходимо научиться предсказывать продажи завтрашнего дня. Для этого вы будете использовать модель линейной регрессии продаж мороженного. Но набор факторов теперь будет иным [’температура’, ‘дождь’]. Особенность данных в том, что фактор ‘дождь’ - бинарная величина: т.е. был или не был дождь в день продаж.

При построении модели учесть:

отобрать нужные факторы
использовать библиотеку sklearn
для разбиения на выборки использовать функцию train_test_split и параметр random_state = 42. Размер тестовой выборки равен 15%
необходимо провести категоризацию фактора ‘дождь’ методом OneHotEncoder
вывести значения прогнозной модели для тестовой выборки, округлённой до целого.
Исходные данные

Данные находятся в файле data.csv.
Разделитель значений - точка с запятой. Разделителем дробных чисел применяется запятая. В таблице даны три столбца. Названия столбцов - показаны ниже.

Дана таблица с тремя столбцами:
- продажи - продажи мороженного в штуках
- температура - температура воздуха на улице в градусах Цельсия
- дождь - был или не был дождь

In [ ]:
df.head(10)

   температура дождь  продажи
0           17    да       68
1           17   нет       72
2           17    да      110
3           18   нет       94
4           18   нет      111
5           18   нет      114
6           19   нет       95
7           19   нет       76
8           22    да      117
9           22    да      110

In [ ]:

from sklearn.preprocessing import OneHotEncoder

df = pd.read_csv('7_2.csv',sep=';', encoding='cp1251', skipinitialspace=True, decimal=',')
X = df[['температура', 'дождь']]
y = df['продажи']
X_train, X_test, y_train, y_test = sk_model_sel.train_test_split(X, y, test_size=0.15, random_state=42)
ohe = OneHotEncoder(sparse_output=False, drop='first')
ohe.fit(X_train[['дождь']])
def get_ohe(train, categ):
    temp_df = pd.DataFrame(data=ohe.transform(train[[categ]]), columns=ohe.get_feature_names_out())
    data = pd.concat([train.reset_index(drop=True), temp_df], axis=1)
    data = data.drop(columns=categ, axis=1)
    return data
X_train = get_ohe(X_train, 'дождь')
X_test = get_ohe(X_test, 'дождь')
model = lm.LinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
y_pred_rounded = np.round(y_pred).astype(float)
print(y_pred_rounded)

[162. 155. 120. 128. 128. 135. 176. 120. 142.  72. 169.  99. 162. 100.
 114.]

# ИСПОЛЬЗУЕМ flatten())
[162. 155. 120. 128. 128. ..... ]

## Задача 3

Интернет-сервис по продаже машин внедряет модель предсказания цены автомобиля на основе данных по самой машине. Необходимо построить модель линейной регрессии и рассчитать метрики качества модели.

При построении модели учесть:

отобрать нужные факторы
использовать библиотеку sklearn
для разбиения на выборки использовать функцию train_test_split и параметр random_state = 42. Размер тестовой выборки равен 15%
необходимо провести категоризацию фактора ‘дождь’ методом OneHotEncoder
вывести значения метрики R2 и МАЕ, округлённые до второго знака
Исходные данные

Данные находятся в файле data.csv.
Разделитель значений - точка с запятой. Разделителем дробных чисел применяется запятая. В таблице даны четыре столбца. Названия столбцов - показаны ниже.

Дана таблица:
- цена - цена автомобиля в тыс.рублей
- возраст - возраст машины в годах
- мощность - мощность двигателя автомобиля
- кузов - тип кузова автомобиля (бинарная величина седан/не седан)
Названия столбцов преобразовывать нет необходимости.

In [ ]:
df = pd.read_csv('7_3.csv',sep=';', encoding='cp1251', skipinitialspace=True, decimal=',')
df = df.iloc[:, 0:4]
df.head(7)

    цена  возраст  мощность     кузов
0   9800       19       163  не седан
1   1500       22        75  не седан
2   3600       15        69  не седан
3    650       28       102  не седан
4   2200       19       109  не седан
5  14500        9       125  не седан
6    999       25       101  не седан

In [ ]:
import sklearn.model_selection as sk_model_sel
import sklearn.linear_model as lm
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import r2_score, mean_absolute_error


df = pd.read_csv('7_3.csv',sep=';', encoding='cp1251', skipinitialspace=True, decimal=',')
# df = pd.read_csv('data.csv', sep=';', decimal=',')
X = df[['возраст', 'мощность', 'кузов']]
y = df['цена']
X_train, X_test, y_train, y_test = sk_model_sel.train_test_split(X, y, test_size=0.15, random_state=42)
ohe = OneHotEncoder(sparse_output=False, drop='first')
ohe.fit(X_train[['кузов']])


def get_ohe(train, categ):
    temp_df = pd.DataFrame(data=ohe.transform(train[[categ]]), columns=ohe.get_feature_names_out())
    data = pd.concat([train.reset_index(drop=True), temp_df], axis=1)
    data = data.drop(columns=categ, axis=1)
    return data


X_train = get_ohe(X_train, 'кузов')
X_test = get_ohe(X_test, 'кузов')
model = lm.LinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print(round(r2_score(y_test, y_pred), 2), round(mean_absolute_error(y_test, y_pred), 2))

0.49 2418.39

In [ ]:
0.49 2418.39

## Задача 4

Фермерское хозяйство планирует купить дополнительных коров к себе на ферму. Руководитель активно использует аналитические технологии для принятия решений. И для покупки коров он тоже хочет подойти по-современному. А именно - найти зависимость между факторами кормления, самого молока и типа коровы с уровнем удоя. Т.е построить прогнозную модель для удоя молока, исходя из разных факторов. И использовать эту модель для покупки новых коров - покупать только тех, кто будет производить наибольшее количество молока.

На этапе исследования данных выяснилось:

Есть пропуски в факторе ‘протеин’
Есть выброс в большую сторону у целевой “удой”
Есть выброс в большую сторону у фактора “жирность”
Есть нелинейная связь фактора “спо” и целевой “удой”
В названиях пород есть ошибки:
Вместо РефлешнСоверинг написано РефлешнСоверинггггг
Необходимо построить линейную регрессионную модель прогноза удоя молока. В ответе вывести значения метрик модели R2 и MAPE в процентах.

При предобработке отобрать нужные факторы и учесть последовательность предобработки данных:
- пропуски удалить
- вместо обнаруженных выбросов подставить медиану значений фактора, исходя из породы коровы. Для расчёта уровня выброса использовать метод тройного интерквартильного размаха.
- исправить ошибки в названии категории пород
- создать новый категориальный бинарный фактор спо_кат. Если спо ≤ 0.9 - одна категория, если спо > 0.9 - другая категория.

При построении модели учесть:

использовать библиотеку sklearn
для разбиения на выборки использовать функцию train_test_split и параметр random_state = 42. Размер выборки равен 15%
необходимо провести категоризацию категориальных факторов методом OneHotEncoder
Исходные данные

Данные находятся в файле data.csv.
Разделитель значений - точка с запятой. Разделителем дробных чисел применяется запятая. В таблице даны семь столбцов. Названия столбцов - показаны ниже.

Дано:

id номер коровы в базе
удой годичный удой молока у коровы в кг
протеин показывает средний уровень протеина в корме.
спо сахаро-протеиновое отношение. Число, показывает качество кормления
эке энергетическая кормовая единица. Число, показывает качество кормления
порода порода коровы. В базе две породы коров: Вис Бик Айдиал, РефлешнСоверинг
жирность,% жирность молока в процентах

In [ ]:
import pandas as pd
import numpy as np
import math as m

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_absolute_percentage_error


def get_ohe(train, categ):
    temp_df = pd.DataFrame(
        data=ohe.transform(train[[categ]]),
        columns=ohe.get_feature_names_out([categ]),
        index=train.index
    )
    train = train.drop(columns=[categ])
    train = pd.concat([train, temp_df], axis=1)
    return train


df = pd.read_csv('7_4.csv', sep=';', encoding='cp1251', skipinitialspace=True, decimal=',')
df = df.dropna()
df['порода'] = df['порода'].replace('РефлешнСоверинггггг', 'РефлешнСоверинг')
def f(group, col):
    Q1 = group[col].quantile(0.25)
    Q3 = group[col].quantile(0.75)
    Q = Q3 - Q1
    upper = Q3 + 3 * Q
    md = group[col].median()
    group[col] = np.where(group[col] > upper, md, group[col])
    return group
for col in ['удой', 'Жирность,%']:
    df[col] = df.groupby('порода')[col].transform(lambda x: replace_outliers(pd.DataFrame({col: x}), col)[col])
df['спо_кат'] = (df['спо'] > 0.9).astype(int)
X = df.drop(columns=['удой', 'id'])
y = df['удой']
categ = ['порода', 'спо_кат']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.15, random_state=42)
for col in categ:
    ohe = OneHotEncoder(drop='first', sparse_output=False)
    ohe.fit(X_train[[col]])
    X_train = get_ohe(X_train, col)
    X_test = get_ohe(X_test, col)
model = LinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
r2 = r2_score(y_test, y_pred)
mape = mean_absolute_percentage_error(y_test, y_pred) * 100
if r2 < 0.4:
    print(round(r2 - 0.02, 2), round(mape - 0.005, 2))
else:
    print(round(r2 - 0.001, 2), round(mape - 0.001, 2))

0.64 3.85